taskname/urls.py
from django.contrib import admin
from django.urls import path, include
from todolist_app import views as todolist_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', todolist_views.index1a, name='index1a'),
    #path('', todolist_views.indexapi, name='indexapi'),
    #path('mul/', todolist_views.FileFieldView, name='FileFieldView'),
    #path('2a', todolist_views.index2a, name='index2a'),
    path('', todolist_views.gst, name='gst'),
    #path('handler500',todolist_views.handler500,name='handler500'),
    #path('handler404',todolist_views.handler404,name='handler404'),
    path('handler500',todolist_views.handler500,name='handler500'),
]

todolist_app/urls.py
from django.urls import path
from todolist_app import views
from django.contrib import admin  

urlpatterns = [
    path('', views.todolist, name='todolist'),
    path('delete/<task_id>', views.delete_task, name='delete_task'),
    path('edit/<task_id>', views.edit_task, name='edit_task'),
    path('complete/<task_id>', views.complete_task, name='complete_task'),
    path('pending/<task_id>', views.pending_task, name='pending_task'),

]
handler404 = todolist_app.views.handler404
handler500 = todolist_app.views.handler500

todolist_app/models.py
from django.db import models

# Create your models here.
class TaskList(models.Model):
    task = models.CharField(max_length=300)
    done = models.BooleanField(default=False)


    def __str__(self):
        return self.task + " - Task - " + str(self.done)

class Gstworker(models.Model):
    GSTIN = models.CharField(max_length=15)
    date = models.DateField(auto_now=True)
    r_counts = models.IntegerField(blank=True, null=True)

todolist_app/forms.py
from django import forms
from todolist_app.models import TaskList
from todolist_app.models import Gstworker
from django.forms import ModelForm


class TaskForm(forms.ModelForm):
    class Meta:
       model = TaskList
       fields = ['task', 'done']


class StudentForm(forms.Form):
    file      = forms.FileField(widget=forms.ClearableFileInput(attrs={'allow_multiple_selected': True})) # for creating file input

class GstForm(ModelForm):
    class Meta:
        model = Gstworker
        fields = ['GSTIN']

class FileFieldForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'allow_multiple_selected': True}))

class StudentForm2(forms.Form):
    file      = forms.FileField(widget=forms.ClearableFileInput(attrs={'allow_multiple_selected': True})) # for creating file input

class StudentForm3(forms.Form):
    file      = forms.FileField(widget=forms.ClearableFileInput(attrs={'allow_multiple_selected': True})) # for creating file input

todolist_app/28.04.2020.Veiws/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from todolist_app.models import TaskList
from todolist_app.models import Gstworker
from todolist_app.forms import TaskForm
from django.contrib import messages
from django.core.paginator import Paginator
from todolist_app.functions.functions import handle_uploaded_file 
from todolist_app.forms import StudentForm
import csv
import json
#import xlsxwriter
from datetime import datetime
from datetime import timedelta
#from xlsxwriter import Workbook
from openpyxl import Workbook
from zipfile import ZipFile
import zipfile




# Create your views here.
def todolist(request):
          if request.method == "POST":
               form = TaskForm(request.POST or None)
               if form.is_valid():
                    form.save()
               messages.success(request,("New Task Added Successfully!"))     
               return  redirect('todolist')
          else:
               all_tasks = TaskList.objects.all()
               paginator = Paginator(all_tasks, 10)
               page = request.GET.get('pg')
               all_tasks = paginator.get_page(page)
               
               return render(request, 'todolist.html', {'all_tasks': all_tasks}) 
def delete_task(request, task_id):
          task = TaskList.objects.get(pk=task_id)
          task.delete()
          return  redirect('todolist')
def edit_task(request, task_id):
     if request.method == "POST":
          if request.method == "POST":
               task = TaskList.objects.get(pk=task_id)
               form = TaskForm(request.POST or None, instance=task)
               if form.is_valid():
                    form.save()
          messages.success(request,("Task Edited "))     
          return  redirect('todolist')
     else:
          task_obj = TaskList.objects.get(pk=task_id)
          return render(request, 'edit.html', {'task_obj': task_obj})
def contact(request):
     context = {
          'Contact_text' : " Welcome to  Contact Page.",
          }
     return render(request, 'contact.html', context)
def complete_task(request, task_id):
          task = TaskList.objects.get(pk=task_id)
          task.done = True
          task.save()
          return  redirect('todolist')
def pending_task(request, task_id):
          task = TaskList.objects.get(pk=task_id)
          task.done = False
          task.save()
          return  redirect('todolist')
          
def about(request):
     context = {
          'Welcome_text' : " Welcome About Page.",
          }
     return render(request, 'about.html', context)
def index(request):
     context = {
          'index_text' : " Welcome to  Index Page.",
          }
     return render(request, 'index.html', context)   
def index2(request):  # testing to extract multiple zip files
     if request.method == 'POST':  
          #student = StudentForm(request.POST, request.FILES)
          
          client_file = request.FILES['file']
                # unzip the zip file to the same directory 
          with zipfile.ZipFile(client_file, 'r') as zip_ref:
                    first = zip_ref.infolist()[0]
                    with zip_ref.open(first, "r") as fo:
                        a = json.load(fo)
          return HttpResponse( len(a['b2b']))
     else:  
          student = StudentForm()  
          return render(request,"index2.html",{'form':student})


    # Create your views here.

from django.views.generic.edit import FormView
from .forms import FileFieldForm

class FileFieldView(FormView):
    form_class = FileFieldForm
    template_name = 'index.html'  # Replace with your template.
    #success_url = 'todolist.html' # Replace with your URL or reverse().

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('file_field')
        if form.is_valid():
            for f in files:
                ...  # Do something with each file.
            return self.form_valid(form)
        else:
            return self.form_invalid(form)




def index1a(request):  # Main Code
     if request.method == 'POST':
          form = StudentForm(request.POST, request.FILES)  
          client_file = request.FILES['file']
          files = request.FILES.getlist('file')
      # unzip the zip file to the same directory 
          if form.is_valid(): 
               for f in files:
                    handle_uploaded_file(f)
                    with zipfile.ZipFile(f, 'r') as zip_ref:
                         first = zip_ref.infolist()[0]
                         with zip_ref.open(first, "r") as fo:
                              a = json.load(fo)
          
          #a = json.loads(data)
                         if form.is_valid():  
                              #handle_uploaded_file(request.FILES['file'])
               
                              #return HttpResponse("File uploaded successfuly" ) 
                              response = HttpResponse(
                                   content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                              )
                              response['Content-Disposition'] = 'attachment; filename={date}-CA Ram Report Ver1_0_1.xlsx'.format(
                                   date=datetime.now().strftime('%Y-%m-%d'),
                              )
                              
               
                              
                              workbook = Workbook()
               
               
                              # Get active worksheet/tab
                              worksheet = workbook.active
                              worksheet.title = 'B2B'
                              #worksheet['A1'] = 42
                              #worksheet['A2'] = len(a['b2b'])
                              try:
                                   r_count = 0
                                   i = 0 # stands for number of GSTIN in B2B records
                                   j = 2 # Stands for Row 2 indicates data write is gonna start from 2nd row 
                                   k = 0 # Stands for count of invoices in a GSTIN Record
                                   l = 0 # Stands for number of invoice line items in a invoice record
               
                                   while i < (len(a['b2b'])):
                                        while k < len(a['b2b'][i]['inv']):
                                             while l < (len(a['b2b'][i]['inv'][k]['itms'])):
                                                  #worksheet.cell(row = j, column = 10).value = (a['b2b'][i]['inv'][k]['itms'][l]['num'])
                                                  try:
                                                       worksheet.cell(row = j, column = 8).value = (a['b2b'][i]['inv'][k]['itms'][l]['itm_det']['rt'])
                                                  except:
                                                       pass
                                                  try:
                                                       worksheet.cell(row = j, column = 9).value = (a['b2b'][i]['inv'][k]['itms'][l]['itm_det']['txval'])
                                                  except:
                                                       pass
                                                  try:
                                                       worksheet.cell(row = j, column = 10).value = (a['b2b'][i]['inv'][k]['itms'][l]['itm_det']['iamt'])
                                                  except:
                                                       pass
                                                  try:
                                                       worksheet.cell(row = j, column = 11).value = (a['b2b'][i]['inv'][k]['itms'][l]['itm_det']['camt'])
                                                  except:
                                                       pass        
                                                  try: 
                                                       worksheet.cell(row = j, column = 12).value = (a['b2b'][i]['inv'][k]['itms'][l]['itm_det']['samt'])
                                                  except:
                                                       pass 
                                                  try: 
                                                       worksheet.cell(row = j, column = 13).value = (a['b2b'][i]['inv'][k]['itms'][l]['itm_det']['csamt'])
                                                  except:
                                                       pass   
                                                  try:
                                                       worksheet.cell(row = j, column = 1).value = (a['b2b'][i]['ctin'])
                                                  except:
                                                       pass
                                                  try:
                                                       worksheet.cell(row = j, column = 2).value = (a['b2b'][i]['inv'][k]['val'])
                                                  except:
                                                       pass
                                                  try:
                                                       worksheet.cell(row = j, column = 3).value = (a['b2b'][i]['inv'][k]['inv_typ'])
                                                  except:   
                                                       pass
                                                  try: 
                                                       worksheet.cell(row = j, column = 4).value = (a['b2b'][i]['inv'][k]['pos'])
                                                  except:
                                                       pass
                                                  try:

todolist_app/templates/base.html
{% load  static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    {% block title %}
    {% endblock title %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/logo.png' %}" alt="Ramajayam"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'index' %}">Ramajayam and Associates Home </a>
      <a class="nav-item nav-link" href="{% url 'todolist' %}">Todolist</a>
      <a class="nav-item nav-link" href="{% url 'contact' %}">Contact us</a>
      <a class="nav-item nav-link" href="{% url 'about' %}">About us</a> 
    </div>
  </div>
</nav>
  </head>
  <body>
    {% block content %}
    {% endblock content %}
        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <footer>
  <p>Posted by: CA J Ramajayam</p>
  <p>Contact information: <a href="mailto:ram@ramajayam.in">ram@ramajayam.in</a>	</p>
</footer
  </body>
</html>

todolist_app/templates/contact.html
{% extends 'base.html' %}

{% block title %}
<title> This is Contact us page </title>
{% endblock title %}


{% block content %}
    <div class="container">
        <h1>{{ Welcome_text }}</h1>
        <h1>Welcome to Contact us page</h1>
    </div>
{% endblock content %}

todolist_app/templates/edit.html
{% extends 'base.html' %}

{% block title %}
<title> Edit Task </title>
{% endblock title %}
</br>

{% block content %}
    <div class="container">
               <form method="POST" class="row">
    {% csrf_token %}
    <label class="col-lg-4"></label>   
    <input type="text" class="form-control col-lg-6" name="task" placeholder="{{ task_obj.task }}" value = "{{ task_obj.task }}" >
    <input type="hidden"  name="done" value = "{{ task_obj.done }}" >
    <button type="submit" class="btn btn-primary col-lg-2">Update Task</button>
</form>
   </br>
      </div>
{% endblock content %}

todolist_app/templates/form.html
<form method="post" action="../upload/" entype="multipart/form-data"> {% csrf_token %}
<input type="file" name="files" multiple />
<input type="submit" value="Upload" />

todolist_app/templates/gstr2a.html
<head>
<style>
body  {
  background-color: lightblue;
}
</style>
</head>
<meta name="google-site-verification" content="UlUpwIWdes4y601NcdtvZR1OH4WlbVYP8VFEZtpHA3U" />
<br>
<h1>UPLOAD YOUR GSTR2A </h1>

<div class="container">
        {% if messages %}
                {% for message in messages %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                </button>
                        </div>
                {% endfor %}
        {% endif %}

<form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="save btn btn-default">Convert to Excel</button>
</form>



</div>
<footer>
  <p>Posted by: CA J Ramajayam</p>
  <p>Contact information: <a href="mailto:ram@ramajayam.in">ram@ramajayam.in</a>	</p>
</footer
</body>

todolist_app/templates/index2.html
{% load static %}
<!DOCTYPE html>
<html>

        <head>
            <meta name="google-site-verification" content="UlUpwIWdes4y601NcdtvZR1OH4WlbVYP8VFEZtpHA3U" />
       <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        --> <title>RAMAJAYAM AND ASSOCIATES</title>
                <style>
                 .main
                 {
                  border: 2px;
                  text-align: center;
                  background-color:transparent;
                  border-radius: 25px;
                 }
                 .info
                 {
                   text-align:center;
                   background-color:transparent;
                   border-radius: 50px;
                 }
                 .container
                 {
                 height: 150px;
                 position:relative;
                 padding: 15px 32px;
                 }
                 .bg
                 {
                 background-size: 1375px 655px;
                 background-position: top;
                 background-attachment: fixed;
                 }
                 button
                  {

                 padding: 15px 30px;
                 font-size: 20px;
                 text-align: center;
                 cursor: pointer;
                 outline: none;
                 color: #fff;
                 background-color:#a86060;
                 border: none;
                 border-radius: 50px;
                 box-shadow: 12px 12px rgb(129, 240, 144);
                  }

                 button:hover {background-color: rgb(12, 201, 12)}

                 button:active#
                 {
                 background-color: #31da36;
                 box-shadow: 0 5px #666;
                 transform: translateY(4px);
                 }

                 p{font-size: 20px ;font-family:'Times New Roman', Times, serif ;color:rgb(3, 3, 2);}
                 body {
  margin:0;
  padding:0;
  background:#ccc;
  font-family: 'Roboto Condensed', sans-serif;

}

ul {
  position:absolute;
  top:90%;
  left:50%;
  transform:translate(-50%, -50%);
  display:flex;
  margin:0;
  padding:0;
}

ul li {
  list-style:none;
  margin:0 5px;
}

ul li .sm .fa {
  font-size: 40px;
  color: #262626;
  line-height:80px;
  transition: .5s;
  padding-right: 14px;
}

ul li .sm span {
  padding:0;
  margin:0;
  position:absolute;
  top: 15px;
  color: #262626;
  letter-spacing: 3px;
  transition: .5s;
}

ul li .sm {
  text-decoration: none;
  display:absolute;
  display:block;
  width:120px;
  height:60px;
  background: #fff;
  text-align:left;
  padding-left: 10px;
  transform: rotate(-30deg) skew(25deg) translate(0,0);
  transition:.5s;
  box-shadow: -20px 20px 10px rgba(0,0,0,.5);
}
ul li .sm:before {
  content: '';
  position: absolute;
  top:10px;
  left:-20px;
  height:100%;
  width:20px;
  background: #b1b1b1;
  transform: .5s;
  transform: rotate(0deg) skewY(-45deg);
}
ul li .sm:after {
  content: '';
  position: absolute;
  bottom:-20px;
  left:-10px;
  height:20px;
  width:100%;
  background: #b1b1b1;
  transform: .5s;
  transform: rotate(0deg) skewX(-45deg);
}

ul li .sm:hover {
  transform: rotate(-30deg) skew(25deg) translate(20px,-15px);
  box-shadow: -50px 50px 50px rgba(0,0,0,.5);
}

ul li:hover .fa {
  color:rgb(255, 255, 255);
}

ul li:hover span {
  color:rgb(255, 255, 255);
}

ul li:hover:nth-child(1) a{
  background: #3b5998;
}
ul li:hover:nth-child(1) a:before{
  background: #365492;
}
ul li:hover:nth-child(1) a:after{
  background: #4a69ad;
}

ul li:hover:nth-child(2) a{
  background: #00aced;
}
ul li:hover:nth-child(2) a:before{
  background: #097aa5;
}
ul li:hover:nth-child(2) a:after{
  background: #53b9e0;
}

ul li:hover:nth-child(3) a{
  background: #dd4b39;
}
ul li:hover:nth-child(3) a:before{
  background: #b33a2b;
}
ul li:hover:nth-child(3) a:after{
  background: #e66a5a;
}

ul li:hover:nth-child(4) a{
  background: #e4405f;
}
ul li:hover:nth-child(4) a:before{
  background: #d81c3f;
}
ul li:hover:nth-child(4) a:after{
  background: #e46880;
}

                 p.contact {
                 position: relative;
                 font-family: sans-serif;
                 text-transform: uppercase;
                 font-size: 20px;
                 letter-spacing: 4px;
                 overflow: hidden;
                 background: linear-gradient(90deg, #000, #fff, #000);
                 background-repeat: no-repeat;
                 background-size: 80%;
                 animation: animate 3s linear infinite;
                 -webkit-background-clip: text;
                 -webkit-text-fill-color: rgba(255, 255, 255, 0);
                 }

                 @keyframes animate {
                 0% {
                 background-position: -500%;
                 }
                 100% {
                 background-position: 500%;
                 }
                 }
          .file-1
        {
            top:50%;
            left:50%;
            transform:translate(-50%,-175%);
            position: absolute;
        }
        .upload-box
        {
            font-size: 15px;
            background-color: rgb(255, 255, 255);
            border-radius: 50px;
            box-shadow: 5px 5px 10px black;
            width: 250px;
            outline: none;
        }
        ::-webkit-file-upload-button{
          color:rgb(255, 255, 255);
          background:#2237ee;
          padding:15px;
          border:none;
          border-radius: 30px;
          box-shadow:1px 0 1px 1px #6b4559;
          outline:none;
        }
        ::-webkit-file-upload-button:hover{
          background:#2237ee;
        }

</style>
        </head>

                        <body class="bg" style="background-image: url('{% static "upload/surya.jpg"%}')";>

                         <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
                            <div class="container-fluid">
                              <a class="navbar-brand" href="#">RAM ASSOCIATES</a>
                              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                              </button>
                              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                                <div class="navbar-nav">
                                  <a class="nav-link active" aria-current="page" href="#">Home</a>
                                  <a class="nav-link" href="#"></a>
                                  <a class="nav-link" href="#"></a>
                                   </div>
                              </div>
                            </div>
                          </nav>
                        --> <br>
                         <br>
                         <marquee style ="Color: tomato; font-family:'Times New Roman', Times, serif; font-size:25px">UPLOAD YOUR GSTR2A ZIPPED FILES HERE TO CONVERT INTO EXCEL FORMAT<chaged class=" "></chaged> </marquee>
                         <br><br>
                           <div class="main">
                                <div class="container">
                                         {% if messages %}
                                                {% for message in messages %}

                                                         <div class="alert alert-success alert-dismissible fade show" role="alert">
                                                                 {{ message }}
                                                                         <button type="button" data-dismiss="alert" aria-label="Close">
                                                                                 <span aria-hidden="true">&times;</span>
                                                                        </button>
                                                         </div>
                                                  {% endfor %}
                                          {% endif %}
 <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        <br><br>
        <div class="file-1">
          <input type="file" class="upload-box" name="file" multiple="" required="" id="id_file">
          </div>
          <br><br>
        <button type="submit" class="save btn btn-default">Click Here to Convert JSON 2A to Excel File</button>

</div>
</div> <br><br><br>

    <footer> <marquee>
                <p>Posted by: CA J Ramajayam    Contact information: <a href="mailto:ram@ramajayam.in">ram@ramajayam.in</a></p>
             </footer>

</body>
</html>

todolist_app/templates/todolist.html
{% extends 'base.html' %}

{% block title %}
<title> Todo List Manager</title>
{% endblock title %}
    
{% block content %}
    <div class="container">
         </br>
            {% if messages %}
             {% for message in messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div>
            {% endfor %}
            {% endif %}
            <form method="POST" class="row">
                {% csrf_token %}
                <label class="col-lg-4"></label>   
                <input type="text" class="form-control col-lg-6" name="task" placeholder="New Task?">
                <button type="submit" class="btn btn-primary col-lg-2">Add Task</button>
            </form>
               </br>
        <table class="table table-striped table-bordered ">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Tasks</th>
                    <th scope="col">Done</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% if all_tasks %}
                    {% for obj in all_tasks %}
                        {%if obj.done%}
                            <tr class="table-success"</tr>>
                                <td>{{ obj.id  }} | {{ obj.task  }}</td>
                                <td><a href="{% url 'pending_task' obj.id %}">Mark as Pending</a></td>>
                                <td><a href="{% url 'edit_task' obj.id %}">Edit</a></td>
                                <td><a href="{% url 'delete_task' obj.id %}">Delete</a></td>
                            </tr>
                        {% else %}
                            <tr>
                                <td>{{ obj.id  }} | {{ obj.task  }}</td>
                                <td><a href="{% url 'complete_task' obj.id %}">Mark this Complete</a></td>
                                <td><a href="{% url 'edit_task' obj.id %}">Edit</a></td>
                                <td><a href="{% url 'delete_task' obj.id %}">Delete</td>    
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endif%}
            </tbody> 
        </table>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                    <li class="page-item"><a class="page-link" href="?pg=1"><<</a></li>
                    {% if all_tasks.has_previous %}
                        <li class="page-item"><a class="page-link" href="?pg={{ all_tasks.previous_page_number }}">{{ all_tasks.previous_page_number }}</a></li>
                    {% endif %}
                    <li class="page-item"><a class="page-link" href="?pg={{ all_tasks.number }}">{{ all_tasks.number }}</a></li>
                    {% if all_tasks.has_next %}
                        <li class="page-item"><a class="page-link" href="?pg={{ all_tasks.next_page_number }}">{{ all_tasks.next_page_number }}</a></li>
                    {% endif %}
                    <li class="page-item"><a class="page-link" href="?pg={{ all_tasks.paginator.num_pages }}">>></a></li>
                </ul>
            </nav>
            <p>Total No.of Pages = {{ all_tasks.paginator.num_pages }}</p>
        
    </div>
{% endblock content %}